### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by neilmayhew**
These came out of looking at @spl's recent issues and PRs.

---
This change is [Reviewable](https://reviewable.io/reviews/silnrsi/teckit/11)

### CODE REVIEW

**Review by devosb — APPROVED** [review]
I did not realise `==` was a bash-ism. Thanks.

**Review by devosb — APPROVED** [review]
You were faster than I. Thanks.

**Review by devosb — APPROVED** [review]
I wish I had known about `/usr/bin/env` in university, it might have helped with all the different systems I had accounts on that put shells in different locations.

**Review by devosb — APPROVED** [review]
Again, you were faster. Thanks.

**Comment by spl** [comment]
Glad I could inspire some improvement! 😄 🎉

**Pull request merged**
