### PR TITLE
Ignore generated files

### PR DESCRIPTION
**Pull request by spl**
Add some files to `.gitignore`.

### CODE REVIEW

**Comment by devosb** [comment]
Except for the file `test-driver`, all the other files you added to `.gitignore` only occur in build directories (AFAIKT). So do the other files really need to be listed? Or did I miss something?

I appreciate you looking at this, I reviewed the build system and found that I should be excluding other build directories (such as `windows-build32` and `windows-build64`). Also I build linux binaries in `./build` which is not ignored but `./linux-build` is already ignored so I should use that.

**Comment by spl** [comment]
Here is the list of untracked files that I see with `git status` after a build before this change:

```
        Makefile
        SFconv/.deps/
        SFconv/.dirstamp
        SFconv/expat/xmlparse/.deps/
        SFconv/expat/xmltok/.deps/
        SFconv/sfconv-SFconv.o
        SFconv/sfconv-UtfCodec.o
        bin/.libs/
        bin/Makefile
        bin/sfconv
        bin/teckit_compile
        bin/txtconv
        config.h
        config.log
        config.status
        docs/Makefile
        lib/.libs/
        lib/Makefile
        lib/libTECkit.la
        lib/libTECkit_Compiler.la
        libtool
        source/.deps/
        source/.dirstamp
        source/.libs/
        source/Engine.lo
        source/Sample-tools/.deps/
        source/Sample-tools/.dirstamp
        source/Sample-tools/TECkit_Compile.o
        source/Sample-tools/TxtConv.o
        source/UnicodeNames.lo
        stamp-h1
        teckit-uninstalled.pc
        teckit.pc
        test-driver
        test/Makefile
        zlib-1.2.3/.deps/
```

I'm on macOS, and I don't know if that makes a difference.

Also, I pushed an update to simplify ignoring `/bin`.

It may be that I missed files that would show up in other build configurations: I didn't do an exhaustive check. But I think what I've added here does improve things a bit. There may certainly be a way to improve upon this.

**Comment by neilmayhew** [comment]
It looks like you're doing an in-tree build instead of an out-of-tree build. When I do the following:

```
./autogen.sh
mkdir linux-build
cd linux-build
../configure
make
git status
```

I get:

```
test-driver
```

**Comment by devosb** [comment]
I like @neilmayhew's out-of-tree build better. Indeed, that is what the suggested build scripts already implement. I will update the documentation at some point to better explain the out-of-tree suggestion.

**Comment by spl** [comment]
I didn't know the out-of-tree build was preferred. Thanks!

**Pull request closed without merging**
